#script: 
#  - docker run --rm -it -v /srv/gitlab-runner/config:/etc/gitlab-runner gitlab/gitlab-runner register
[[runners]]
  (...)
  executor = "docker"
  [runners.docker]
    (...)
    helper_image = "my.registry.local/gitlab/gitlab-runner-helper:x86_64-v${CI_RUNNER_VERSION}"

session_server:
  - listen_address = "https://gitlab.com/mrgofuckyourself/reboot6:8093"
  - advertise_address = "shared-runners-manager-5.gitlab.com:8093"
  - session_timeout = 1800

terminal:
  image: debian:latest
  before_script:
    - apt update -y
  script:
    - sleep 60
