session_server:
  listen_address = "[::]:8093"
  advertise_address = "runner-host-name.tld:8093"
  session_timeout = 1800

terminal:
  image: debian:latest
  before_script:
    - apt update -y
  script:
    - sleep 60
  variables:
    ENV: "test"
