script: 
  - docker run --rm -it -v /srv/gitlab-runner/config:/etc/gitlab-runner gitlab/gitlab-runner register


session_server:
  - listen_address = "https://gitlab.com/mrgofuckyourself/reboot6:8093"
  advertise_address = "runner-mrgofuckyourself.tld:8093"
  session_timeout = 1800

terminal:
  image: debian:latest
  before_script:
    - apt update -y
  script:
    - sleep 60
