terminal:
  # This can be any image that has the necessary runtime environment for your project.
  image: debian:latest
  before_script:
    - apt update -y
  script: sleep 60
  variables:
    ENV: "test"
